// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using s14112310482.Data;

#nullable disable

namespace s14112310482.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("s14112310482.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Memo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Memo = "礦坑",
                            Name = "主世界"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Memo = "地獄",
                            Name = "下界"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Memo = "末地",
                            Name = "終界"
                        });
                });

            modelBuilder.Entity("s14112310482.Models.ImgCarousel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImgF")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ImgCarousels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImgF = "a1.png"
                        },
                        new
                        {
                            Id = 2,
                            ImgF = "a2.png"
                        },
                        new
                        {
                            Id = 3,
                            ImgF = "a3.png"
                        },
                        new
                        {
                            Id = 4,
                            ImgF = "a4.png"
                        },
                        new
                        {
                            Id = 5,
                            ImgF = "a5.png"
                        },
                        new
                        {
                            Id = 6,
                            ImgF = "a6.png"
                        },
                        new
                        {
                            Id = 7,
                            ImgF = "a7.png"
                        });
                });

            modelBuilder.Entity("s14112310482.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Difficulty")
                        .HasColumnType("float");

                    b.Property<string>("ImgF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "遠古遺跡BOSS，潛藏危機與寶藏。",
                            Difficulty = 7.0,
                            ImgF = "e1.png",
                            Name = "伏守者"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "烈焰燃燒，危機四伏的堡壘。",
                            Difficulty = 5.0,
                            ImgF = "q1.png",
                            Name = "地獄堡壘"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "遺落空島，探索神秘終界城。",
                            Difficulty = 9.0,
                            ImgF = "w1.png",
                            Name = "終界城"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "幽匿遺跡伏守危險寶庫",
                            Difficulty = 9.0,
                            ImgF = "e2.png",
                            Name = "遠古城市"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "探秘考驗解謎奪寶生存",
                            Difficulty = 7.0,
                            ImgF = "e3.png",
                            Name = "試煉密室"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "晶石洞穴探險挖礦尋寶",
                            Difficulty = 7.0,
                            ImgF = "e4.png",
                            Name = "紫晶洞"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "高塔刷怪狩獵挑戰生存",
                            Difficulty = 9.0,
                            ImgF = "e5.png",
                            Name = "試煉密室生怪塔"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "廢棄傳送門幽暗生存戰",
                            Difficulty = 9.0,
                            ImgF = "q2.png",
                            Name = "廢棄傳送門"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "豬靈要塞危險尋寶挑戰",
                            Difficulty = 6.0,
                            ImgF = "q3.png",
                            Name = "堡壘遺跡"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Description = "終界入口激活冒險終章",
                            Difficulty = 6.0,
                            ImgF = "w2.png",
                            Name = "終界傳送門"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "虛空島嶼龍巢巔峰決戰",
                            Difficulty = 8.0,
                            ImgF = "w3.png",
                            Name = "終界"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Description = "終界霸主黑翼終極龍戰",
                            Difficulty = 10.0,
                            ImgF = "w4.png",
                            Name = "終界龍"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
